### ISSUE TITLE
Add `reth` to fuzzers

### ISSUE THREAD

**Issue by holiman** [holiman/goevmlab#113]
Would be nice to add `reth`. 

1. We need to be able to execute `reth` (or a reth-based binary) with a statetest as input. 
2. During execution, it needs to spit out `jsonl` per-opcode traces. 

Is https://github.com/bluealloy/revm the thing to use? 

cc @rakita @gakonst

Also, I need some build instructions. 

The first step, after building it, would be to generate the outputs, based on the reference tests: https://github.com/holiman/goevmlab/tree/master/evms/testdata . That is, doing this, but for reth; https://github.com/holiman/goevmlab/blob/master/evms/testdata/run.sh . 

Once we have the outputs, it's pretty easy to see if any particular tweaking in a reth-specific shim is needed.

**Comment by holiman** [comment]
See also https://github.com/ethereum/evmlab/wiki/howto-evm#fuzzing-input (everything above "Fuzzing input" can be ignored)

**Comment by holiman** [comment]
Followed these steps
```
git clone https://github.com/bluealloy/revm.git
cd revm
cargo build --release

...
   Compiling revm-primitives v1.3.0 (/home/user/workspace/revm/crates/primitives)
   Compiling revm-precompile v2.2.0 (/home/user/workspace/revm/crates/precompile)
   Compiling revm-interpreter v1.3.0 (/home/user/workspace/revm/crates/interpreter)
   Compiling revm v3.5.0 (/home/user/workspace/revm/crates/revm)
    Finished release [optimized + debuginfo] target(s) in 11.56s
```
But I don't see where the actual `revm` binary is.

**Comment by rakita** [comment]
> Followed these steps
> 
> ```
> git clone https://github.com/bluealloy/revm.git
> cd revm
> cargo build --release
> 
> ...
>    Compiling revm-primitives v1.3.0 (/home/user/workspace/revm/crates/primitives)
>    Compiling revm-precompile v2.2.0 (/home/user/workspace/revm/crates/precompile)
>    Compiling revm-interpreter v1.3.0 (/home/user/workspace/revm/crates/interpreter)
>    Compiling revm v3.5.0 (/home/user/workspace/revm/crates/revm)
>     Finished release [optimized + debuginfo] target(s) in 11.56s
> ```
> 
> But I don't see where the actual `revm` binary is.



> Followed these steps
> 
> ```
> git clone https://github.com/bluealloy/revm.git
> cd revm
> cargo build --release
> 
> ...
>    Compiling revm-primitives v1.3.0 (/home/user/workspace/revm/crates/primitives)
>    Compiling revm-precompile v2.2.0 (/home/user/workspace/revm/crates/precompile)
>    Compiling revm-interpreter v1.3.0 (/home/user/workspace/revm/crates/interpreter)
>    Compiling revm v3.5.0 (/home/user/workspace/revm/crates/revm)
>     Finished release [optimized + debuginfo] target(s) in 11.56s
> ```
> 
> But I don't see where the actual `revm` binary is.

The binary is `revme` so the command should be `cargo build --release --package revme` and the binary will be found in `target/release/revme`, command for running binaries looks like: `./target/release/revme statetest ./path_to_folder`.

I think we are missing omit memory/stack flags and maybe we should match the order of fields in json but eth statetests are run on every PR and stateroot is checked.

If you want to run directly with cargo here is command: `https://github.com/bluealloy/revm?tab=readme-ov-file#running-eth-tests`

**Comment by gakonst** [comment]
gm - ack and we'll prio thx Martin. more soon.

**Comment by holiman** [comment]
> I think we are missing omit memory/stack flags and maybe we should match the order of fields in json but eth statetests are run on every PR and stateroot is checked.

Fuzzer needs stack, so no need to omit it. It doesn't actually check memory though, so it usually speeds things up if we can omit it. Field-order doesn't matter.

**Comment by holiman** [comment]
Seems that it requires `sender`. 
```
./target/release/revme statetest ~/workspace/goevmlab/evms/testdata/cases/statetest_filled.json 

Running tests in /home/user/workspace/goevmlab/evms/testdata/cases/statetest_filled.json...
1/1Finished execution. Total CPU time: 0.000000s
Error: Statetest(TestError { name: "/home/user/workspace/goevmlab/evms/testdata/cases/statetest_filled.json", kind: SerdeDeserialize(Error("missing field `sender`", line: 47, column: 5)) })
```
Others typically take `sender` as a shortcut if it exists, but it's not a requirement.

**Comment by holiman** [comment]
It doesn't like the `out` field :) 
```
user@debian-work:~/workspace/revm$ ./target/release/revme statetest /tmp/foo-naive-0000.json 

Running tests in /tmp/foo-naive-0000.json...
█████████████████████████████████████████████████████████████████████████████████████████████████████████ 1/1Finished execution. Total CPU time: 0.000000s
Error: Statetest(TestError { name: "/tmp/foo-naive-0000.json", kind: SerdeDeserialize(Error("unknown field `out`, expected one of `_info`, `env`, `pre`, `post`, `transaction`", line: 49, column: 7)) })

user@debian-work:~/workspace/revm$ cat  /tmp/foo-naive-0000.json  | jq . 
```
```json
{
  "foo-naive-0000": {
    "env": {
      "currentCoinbase": "b94f5374fce5edbc8e2a8697c15331677e6ebf0b",
      "currentDifficulty": "0x200000",
      "currentRandom": "0x0000000000000000000000000000000000000000000000000000000000020000",
      "currentGasLimit": "0x26e1f476fe1e22",
      "currentNumber": "0x1",
      "currentTimestamp": "0x3e8",
      "previousHash": "0x044852b2a670ade5407e78fb2863c51de9fcb96542a07186fe3aeda6bb8a116d",
      "currentBaseFee": "0x10"
    },
    "pre": {
      "0x00000000000000000000000000000000000000f1": {
        "code": "0x60e360ce60a96040603060556007345097191c5633061b6c833a085836737a3e5405121a5b480510178c897d6da34736086a9f7a6e74577518368b90ff1c5140421b8e77527c365868188a8651803900949134786a7510fa391a6f838d51038e5b64019058446c073d4069020643f0653a0a118f585068706939016c391c9900871857743f8173197196556811584509398b778c88671568038c509e8efef4873820521d161d6f7b17418f84331683647e3d8685676c0737405716087e18586f658b1d3218356f385210777945309f3af0137676739f4584761232463c7d468f406df56b5bfa1299fe0a758b853e817d1d3236fd7873306ba07e1b51467d388198428a0791581612729d366a7684877a92a3419c6e6b323d7a54403616545943381280417d7f14796454fd703d616539135565a330403f95391d14188d95817b3a56467ffe7d051a78046b6161546f615330036365807e439e88a30a803557319b545b427d3464480b627c1652048d529a8f479f04746f159035614884398893f458637a365293748262128810963775816578847a3d7e8b6c8356168130741772558b906509653032423b683312153f6d9144737786543813155b5412f2833c47fa350a5a727d44383d3b051506697e40fa1d8b475a438b9287877bfe9d5a048e696ea3737e64378575f5620a155b970b6203429672f01b80f50b93715768306d1b3312890056701a7e3520478ffa451d6f8a840a7b7495817b095b2063770a57736c07520b429a52331048f23970ff84596a6f3a436d5a40135a02663744529003529ca0796f3c1a3c6650398d0a9a48609e03f486a37904437645359c19483636123946625168787a347731367430637463f0366656428e90f35730908a7c3c1c7f736d8b515690987c56167d20783ff3831b41121008635983ff3406988aff6e65810770866d1c86333e107e629768591c458d0389988b5a77a1a4516d15845b70a17a361a761d8384631a380214907c8114f29935357f121d5a6809021118917614885b9443643f6a8c0006568a8964337157f23754351184a26c3962fe133fff1d6100fe134465385b427f164412f4fd99370260811209fa80648a187a6753f11c6b040b5b0810607af24172067f528667127d0754437e63636255483c3130975b9b323d747e6f3656169d8719641762f17a857a90916a3a6a48905b09a103511d8b1710605b1306539a6cf32060743f738a3838460a800b6e8417f1373d506d7b586e8d90ff6d1169995843fa74128f83a303370b54535b7a8e1701609b10377c1a6a1547a16ef48d6c55747d1a8438fe3310a20b39a3016442876c9f547735843f14485107576d386b648287386f7c1b3588018a31838b709666567e5b561d7e8ef432341a8468815ba3799a7f876e341a7a80358f5a029110151a9b",
        "storage": {
          "0x0000000000000000000000000000000000000000000000000000000000000000": "0x000000000000000000000000000000000000000000000000000000000000000e",
          "0x0000000000000000000000000000000000000000000000000000000000000002": "0x000000000000000000000000000000000000000000000000000000000000000e",
          "0x0000000000000000000000000000000000000000000000000000000000000003": "0x0000000000000000000000000000000000000000000000000000000000000006",
          "0x0000000000000000000000000000000000000000000000000000000000000005": "0x000000000000000000000000000000000000000000000000000000000000000e",
          "0x0000000000000000000000000000000000000000000000000000000000000007": "0x0000000000000000000000000000000000000000000000000000000000000008"
        },
        "balance": "0x0",
        "nonce": "0x0"
      },
      "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
        "code": "0x",
        "storage": {},
        "balance": "0xffffffffff",
        "nonce": "0x0"
      }
    },
    "transaction": {
      "gasPrice": "0x10",
      "nonce": "0x0",
      "to": "0x00000000000000000000000000000000000000f1",
      "data": [
        "0x"
      ],
      "gasLimit": [
        "0x7a1200"
      ],
      "value": [
        "0x"
      ],
      "sender": "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b",
      "secretKey": "0x45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8"
    },
    "out": "0x",
    "post": {
      "Merge": [
        {
          "hash": "0x25eadaabd517fb62a141baa3708197c6c3b3ec2402f32a2a1aee465b40c1462e",
          "logs": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
          "indexes": {
            "data": 0,
            "gas": 0,
            "value": 0
          }
        }
      ]
    }
  }
}
```

**Comment by holiman** [comment]
If I drop the `out` field, it is missing the `_info` field. Why does it need that? IIRC it's only a bit of metadata? 

```
user@debian-work:~/workspace/revm$ ./target/release/revme statetest ./foo.json 

Running tests in ./foo.json...
█████████████████████████████████████████████████████████████████████████████████████████████████████████ 1/1Finished execution. Total CPU time: 0.000000s
Error: Statetest(TestError { name: "./foo.json", kind: SerdeDeserialize(Error("missing field `_info`", line: 62, column: 3)) })
```

**Comment by holiman** [comment]
If put a dummy `"_info":{}` there, it runs the test. 
```
 ./target/release/revme statetest --json  ./foo.json  2>/dev/null

Running tests in ./foo.json...
{"depth":1,"pc":0,"opName":"PUSH1","op":96,"gas":"0x79bff8","gasCost":"0x0","memSize":0,"stack":[]}
{"depth":1,"pc":2,"opName":"PUSH1","op":96,"gas":"0x79bff5","gasCost":"0x79bff5","memSize":0,"stack":["0xe3"]}
{"depth":1,"pc":4,"opName":"PUSH1","op":96,"gas":"0x79bff2","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce"]}
{"depth":1,"pc":6,"opName":"PUSH1","op":96,"gas":"0x79bfef","gasCost":"0x79bfef","memSize":0,"stack":["0xe3","0xce","0xa9"]}
{"depth":1,"pc":8,"opName":"PUSH1","op":96,"gas":"0x79bfec","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40"]}
{"depth":1,"pc":10,"opName":"PUSH1","op":96,"gas":"0x79bfe9","gasCost":"0x79bfe9","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30"]}
{"depth":1,"pc":12,"opName":"PUSH1","op":96,"gas":"0x79bfe6","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55"]}
{"depth":1,"pc":14,"opName":"CALLVALUE","op":52,"gas":"0x79bfe3","gasCost":"0x79bfe3","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7"]}
{"depth":1,"pc":15,"opName":"POP","op":80,"gas":"0x79bfe1","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7","0x0"]}
{"depth":1,"pc":16,"opName":"SWAP8","op":151,"gas":"0x79bfdf","gasCost":"0x79bfdf","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7"]}
Finished execution. Total CPU time: 0.000258s
All tests passed!
```
However.

1. The ouput should preferrably be _strictly_ `jsonl`. So use either `stdout` or `stderr` for outputtting `jsonl`, and use the other channel for outputting e.g. logs (if you think you need them). 
2. It needs to spit out a stateroot after the last op. Besu-example: https://github.com/holiman/goevmlab/blob/master/evms/testdata/traces/00000006-naivefuzz-0.json.besu.stdout.txt#L910, geth-example: https://github.com/holiman/goevmlab/blob/master/evms/testdata/traces/00000006-naivefuzz-0.json.geth.stderr.txt#L911 
3. If I run it on a test with an erroneous stateroot, it spits out _massive_ amount of info. The fuzzer typically will always operate like this -- we don't need a full state dump, just the stateroot that was calculated. If you want to spit out more info, like state dump, feel free to do so in the *other* chan (stdout/stderr). 

For a failing test, it also prints the traces twice for some reason (?): 
```
Running tests in ./foo.json...
{"depth":1,"pc":0,"opName":"PUSH1","op":96,"gas":"0x79bff8","gasCost":"0x0","memSize":0,"stack":[]}
{"depth":1,"pc":2,"opName":"PUSH1","op":96,"gas":"0x79bff5","gasCost":"0x79bff5","memSize":0,"stack":["0xe3"]}
{"depth":1,"pc":4,"opName":"PUSH1","op":96,"gas":"0x79bff2","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce"]}
{"depth":1,"pc":6,"opName":"PUSH1","op":96,"gas":"0x79bfef","gasCost":"0x79bfef","memSize":0,"stack":["0xe3","0xce","0xa9"]}
{"depth":1,"pc":8,"opName":"PUSH1","op":96,"gas":"0x79bfec","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40"]}
{"depth":1,"pc":10,"opName":"PUSH1","op":96,"gas":"0x79bfe9","gasCost":"0x79bfe9","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30"]}
{"depth":1,"pc":12,"opName":"PUSH1","op":96,"gas":"0x79bfe6","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55"]}
{"depth":1,"pc":14,"opName":"CALLVALUE","op":52,"gas":"0x79bfe3","gasCost":"0x79bfe3","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7"]}
{"depth":1,"pc":15,"opName":"POP","op":80,"gas":"0x79bfe1","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7","0x0"]}
{"depth":1,"pc":16,"opName":"SWAP8","op":151,"gas":"0x79bfdf","gasCost":"0x79bfdf","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7"]}

Traces:
{"depth":1,"pc":0,"opName":"PUSH1","op":96,"gas":"0x79bff8","gasCost":"0x0","memSize":0,"stack":[]}
{"depth":1,"pc":2,"opName":"PUSH1","op":96,"gas":"0x79bff5","gasCost":"0x79bff5","memSize":0,"stack":["0xe3"]}
{"depth":1,"pc":4,"opName":"PUSH1","op":96,"gas":"0x79bff2","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce"]}
{"depth":1,"pc":6,"opName":"PUSH1","op":96,"gas":"0x79bfef","gasCost":"0x79bfef","memSize":0,"stack":["0xe3","0xce","0xa9"]}
{"depth":1,"pc":8,"opName":"PUSH1","op":96,"gas":"0x79bfec","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40"]}
{"depth":1,"pc":10,"opName":"PUSH1","op":96,"gas":"0x79bfe9","gasCost":"0x79bfe9","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30"]}
{"depth":1,"pc":12,"opName":"PUSH1","op":96,"gas":"0x79bfe6","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55"]}
{"depth":1,"pc":14,"opName":"CALLVALUE","op":52,"gas":"0x79bfe3","gasCost":"0x79bfe3","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7"]}
{"depth":1,"pc":15,"opName":"POP","op":80,"gas":"0x79bfe1","gasCost":"0x0","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7","0x0"]}
{"depth":1,"pc":16,"opName":"SWAP8","op":151,"gas":"0x79bfdf","gasCost":"0x79bfdf","memSize":0,"stack":["0xe3","0xce","0xa9","0x40","0x30","0x55","0x7"]}
...
```

**Comment by holiman** [comment]
> For a failing test, it also prints the traces twice for some reason (?):

Just a thought that I had: this might indicate that the client internally stores the traces before emitting them, or stores while emitting them. I would _not_ recommend doing so -- traces are sometimes _gigantic_, several gigabytes. So just emit and forget -- that is the reason `jsonl` is used as opposed to `json`, the ability to stream.

**Comment by rakita** [comment]
This is amazing, thanks! I'll make sure to add those changes.

Compounded list:
- [ ] Make `_info` optional (I probably didn't bother to make it optional before)
- [ ] Make `sender` optional, it can be recovered from the private key.
- [ ] Be aware of `out` field, and compare it with output of evm.
- [ ] Clean output so it is just `jsonl` (push other lines to `stderr`)
- [ ] Spit out a stateroot (ty for examples)
- [ ] Don't print traces twice (Traces are printed twice as we execute the second time, we don't store them).

**Comment by holiman** [comment]
> Don't print traces twice

Regarding this point -- as soon as goevmlab 'sees' the stateroot, it can skip the remaining output, since obviously the trace is done by that time. So if you absolutely do want to print more data, re-run or do state dump, that's fine from my perspective (but perhaps a bit waste of cpu-time).

**Comment by holiman** [comment]
>  Be aware of out

I don't ever use the `out` field, but I guess it has been used at some point. I think it's ok if you just ignore it.

**Comment by rakita** [comment]
Hey sorry for the long wait, had some priority work that would unblock a few other things.

I just merged changes to revm.

I opted to print out `jsonl` to `stderr`, and will not print them twice if the `--json` flag is active.

**Comment by holiman** [comment]
Great! Now it looks better. When I'm running the reference output-tests, here's the first diff I see

### Blockhash

```
prev:           both: {"depth":1,"pc":79,"gas":7978040,"op":64,"opName":"BLOCKHASH","stack":["0x0","0x0","0x1","0x0","0x3e3d6d5ff042148d326c1898713a76759ca273","0x0"]}
diff:               : {"depth":1,"pc":80,"gas":7978020,"op":65,"opName":"COINBASE","stack":["0x0","0x0","0x1","0x0","0x3e3d6d5ff042148d326c1898713a76759ca273","0x44852b2a670ade5407e78fb2863c51de9fcb96542a07186fe3aeda6bb8a116d"]}
diff:          revm-: {"depth":1,"pc":80,"gas":7978020,"op":65,"opName":"COINBASE","stack":["0x0","0x0","0x1","0x0","0x3e3d6d5ff042148d326c1898713a76759ca273","0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563"]}
```
So, `BLOCKHASH(0)` returns `0x44852b2a670ade5407e78fb2863c51de9fcb96542a07186fe3aeda6bb8a116d` on the other VMs, and `0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563` on revm, while executing statetest. Some googling leads me to believe you are returning `keccak256(0, 32)`. 

More info about blockhash in statetests:
https://github.com/NethermindEth/nethermind/issues/3201 and https://github.com/NethermindEth/nethermind/issues/4967 
Geth seems to use the string-version of the number, `keccak256("0")`:
```golang
func vmTestBlockHash(n uint64) common.Hash {
	return common.BytesToHash(crypto.Keccak256([]byte(big.NewInt(int64(n)).String())))
}
```

I'll pile on more stuff here if I find it

**Comment by holiman** [comment]
Awesome, it's looking good now. I'll let the fuzzer run for a couple of hours, then merge the PR.

**Comment by gakonst** [comment]
Really thank you for taking the time Martin.

**Comment by rakita** [comment]
Thank you Martin!
