### ISSUE TITLE
Docker-based nethermind evm flavour

### ISSUE THREAD

**Issue by holiman** [holiman/goevmlab#12]
From Sebastian Dremo

>  https://hub.docker.com/r/nethermindeth/nethtest this docker will let you run state tests
docker run -t -i <testFile.json>

TODO: add an evm which uses dockerized nethtest under the hood, instead of the `nethtest` binary

**Comment by 0x0elliot** [comment]
this is really interesting to me. i wonder if i can take this up? any basic instructions to begin with would really help me figure this out quickly! @holiman
