### ISSUE TITLE
Improve testing-speed (for fast clients)

### ISSUE THREAD

**Issue by holiman** [holiman/goevmlab#120]
Example when executing with three clients, where one takes 100ms, one 200ms, and one takes 500ms. 
The slowest determines the speed, which become 2 per second, but executed in two threads, so 4 per second:
```
INFO [01-23|09:00:32.640] Executing                                tests=62 time=16.000s test/s=3.9 "avg steps"=4.8 global=52060
INFO [01-23|09:00:32.641] Stats geth-0                             execSpeed=100.5ms longest=108.367159ms
INFO [01-23|09:00:32.641] Stats geth-1                             execSpeed=196.8ms longest=206.793057ms
INFO [01-23|09:00:32.641] Stats geth-2                             execSpeed=483.2ms longest=507.97227ms
```

An alternative way to operate would be to, instead of waiting for all `n` clients to 
finish, wait only for `2` clients (or `3`). Whenever the slowest is ready, it will execute
again, but the faster clients might execute a couple of tests in the meantime. 

Right now, the test execution of client `X` is sent to a particular output stream

```
 client 0 -> outputstreams[0]
 client 1 -> outputstreams[1]
 client 2 -> outputstreams[2]
 ```
Therefore, once all clients are finished, we can compare all output streams. We don't
actually do that, becase the outputstreams are are `dualWriter`s, a special type which 
not only writes to an underlying writer (a file), but also into a hasher. So what we do is 
compare the hashes. In nearly all cases, the hashes match. 

If they do not match, we look at the _actual_ output which was flushed to disk, and expect
to find a consensus flaw. 

This procedure would need to change. 

- Each execution of a test should produce a `hash`, and the actual output discarded. 
- Thereby, a client which is finished with test `M` can continue `N`, `O`.. and 
  we can retain the results until we no longer need it. 
- When we finally compare the hashes, and discover a mismatch, we need to 
  pause the progression, and re-run the failing test, this time on all clients, 
  and with full output-comparison enabled.

**Comment by holiman** [comment]
Here's what I'm using to simulate different clients
```
package main

import (
	"fmt"
	"os"
	"time"
)

func main() {
	time.Sleep(500 * time.Millisecond)
	out := `{"pc":0,"op":96,"gas":"0x4757","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":2,"op":96,"gas":"0x4754","gasCost":"0x3","memSize":0,"stack":["0x0"],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":13,"op":96,"gas":"0xf2","gasCost":"0x3","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1"}
{"pc":15,"op":84,"gas":"0xef","gasCost":"0x834","memSize":0,"stack":["0x3"],"depth":1,"refund":0,"opName":"SLOAD","error":"out of gas"}
{"output":"","gasUsed":"0x4757","error":"out of gas"}
{"stateRoot": "0x75dc56643cc707a2e6c9a4cf7e28061e9598bd02ecac22c406365c058088d59b"}`
	fmt.Fprint(os.Stderr, out)
	fmt.Fprint(os.Stdout, out)
}
```
Can be executed via 
```
 ./generic-fuzzer --geth ./testvm_100 --geth ./testvm_200 --geth ./testvm_500
```

**Comment by yawayl** [comment]
Hello did it work?

**Comment by holiman** [comment]
Like a charm, yes, 10-20x speedup :)
