### ISSUE TITLE
Reth incompatibility

### ISSUE THREAD

**Issue by namiloh** [holiman/goevmlab#125]
Reth has started using hexstrings for `refund`
```
revm err: json: cannot unmarshal string into Go struct field StructLog.refund of type uint64, line
	{"pc":15116,"op":97,"gas":"0x8f","gasCost":"0x8f","stack":["0xd2ea85a5aca10e903871bbaee8d0b01fbd9d25d081071745c45abe812642e38"],"depth":1,"returnData":"0x","refund":"0x0","memSize":"128","opName":"PUSH2"}
```

**Comment by namiloh** [comment]
cc @rakita 
I can fix this in goevmlab though, so not a biggie

**Comment by rakita** [comment]
Yeah it should be a Hex Number like other `gas`, `gas_cost`

**Comment by holiman** [comment]
Ideally, both `refund` and `memSize` are json numbers, just like `depth`. Then I won't have to do things like this: https://github.com/holiman/goevmlab/pull/128/files#diff-69f39b153a7d6574e40be6a6a75bd848f44860faf32cc4cca0d987879d62f9fcR161

**Comment by rakita** [comment]
> Ideally, both `refund` and `memSize` are json numbers, just like `depth`. Then I won't have to do things like this: https://github.com/holiman/goevmlab/pull/128/files#diff-69f39b153a7d6574e40be6a6a75bd848f44860faf32cc4cca0d987879d62f9fcR161

I was referencing the EIP https://eips.ethereum.org/EIPS/eip-3155, imo I would put everything as a number so it is easier to read :)
