### ISSUE TITLE
upgrade to latest geth

### ISSUE THREAD

**Issue by holiman** [holiman/goevmlab#148]
Upgrading to latest geth causes a bit of problems, since the bls-fuzzer uses the now-defunct geth bls package. It needs to be converted, preferrably to use gnark, like https://github.com/ethereum/go-ethereum/pull/29441 . 

@MariusVanDerWijden Could you please take a look at this?

**Comment by MariusVanDerWijden** [comment]
will do

**Comment by holiman** [comment]
Thank you! :pray:
