### ISSUE TITLE
Question: tracing

### ISSUE THREAD

**Issue by revitteth** [holiman/goevmlab#61]
Tracing appears to be a highly useful but delicate area of the client ecosystem, would it be possible to add some tracing to the fuzzer?

**Comment by holiman** [comment]
Well... The fuzzer is really based on tracing, not sure exactly what you mean. After the fuzzer finds an interesting case, it emits the trace-files, which can be investigated manually (or by tracediff/traceview). Don't know what else to do .. ?

**Comment by revitteth** [comment]
Sure, sorry I think I've got some specific cases which we could include which may show some issues tracing transactions/blocks with specific properties.

For example this tx on etherscan (state change tab shows no data): https://etherscan.io/tx/0x2fdf04a1d70c3cfa1f9d89baf080377ca110c5dbc28def63b01e18b270e85f6f#statechange

There is a full discussion here: https://github.com/ledgerwatch/erigon/issues/5306 and it looks like this potentially affects multiple clients.

**Comment by holiman** [comment]
This is unrelated to goevmlab
